In [ ]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.10/dist-packages (3.5.3)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)

In [ ]:
import kagglehub

# Download latest version
path_google = kagglehub.dataset_download("mexwell/google-merchandise-sales-data")
print("Path to dataset files:", path_google)

# Download latest version
path_weather = kagglehub.dataset_download("bwandowando/philippine-cities-weather-data-2000-2009")
print("Path to dataset files:", path_weather)

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.3)
Path to dataset files: /root/.cache/kagglehub/datasets/mexwell/google-merchandise-sales-data/versions/1
Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.3)
Path to dataset files: /root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("ExemploPySpark") \
    .getOrCreate()

In [ ]:
import pandas as pd
df_pandas_google = pd.read_csv("/root/.cache/kagglehub/datasets/mexwell/google-merchandise-sales-data/versions/1/events1.csv")
df_pandas_weather = pd.read_csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv")

In [ ]:
df_pandas_google.head(4)

,user_id,ga_session_id,country,device,type,item_id,date
0,2133,16909,US,mobile,purchase,94,2020-11-01 00:27:14
1,2133,16909,US,mobile,purchase,425,2020-11-01 00:27:14
2,5789,16908,SE,desktop,purchase,1,2020-11-01 01:44:44
3,5789,16908,SE,desktop,purchase,62,2020-11-01 01:44:44

In [ ]:
df_pandas_weather.head(5)

,city_name,latitude,longitude,datetime,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,...,sunshine_duration,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,shortwave_radiation_sum,et0_fao_evapotranspiration
0,Alaminos,16.156111,119.98111,2000-01-01,2.0,29.3,25.4,27.0,33.9,29.6,...,36173.32,0.0,0.0,0.0,0.0,11.2,23.8,138.0,17.25,3.65
1,Alaminos,16.156111,119.98111,2000-01-02,1.0,28.4,24.7,26.3,34.0,29.3,...,36332.58,0.0,0.0,0.0,0.0,13.2,23.4,118.0,17.67,3.54
2,Alaminos,16.156111,119.98111,2000-01-03,0.0,29.0,25.1,26.7,32.6,27.6,...,36335.24,0.0,0.0,0.0,0.0,15.1,29.2,143.0,18.13,4.07
3,Alaminos,16.156111,119.98111,2000-01-04,1.0,29.3,24.8,26.6,31.7,26.7,...,36421.28,0.0,0.0,0.0,0.0,16.7,31.7,143.0,17.29,4.13
4,Alaminos,16.156111,119.98111,2000-01-05,1.0,28.9,24.3,26.3,32.1,26.0,...,36424.74,0.0,0.0,0.0,0.0,19.3,33.5,134.0,18.62,4.32

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("ExemploLeitura").getOrCreate()

# Leitura de um arquivo CSV
df_pyspark = spark.read.csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv", header=True, inferSchema=True)

In [ ]:
#Nomes das colunas
for i in df_pandas_weather.columns:
  print(i)

city_name
latitude
longitude
datetime
weather_code
temperature_2m_max
temperature_2m_min
temperature_2m_mean
apparent_temperature_max
apparent_temperature_min
apparent_temperature_mean
sunrise
sunset
daylight_duration
sunshine_duration
precipitation_sum
rain_sum
snowfall_sum
precipitation_hours
wind_speed_10m_max
wind_gusts_10m_max
wind_direction_10m_dominant
shortwave_radiation_sum
et0_fao_evapotranspiration

In [ ]:
# Seleciona colunas específicas - Pandas
df_selecionado_pandas = df_pandas_weather[['city_name', 'latitude', 'longitude', 'weather_code','temperature_2m_max', 'temperature_2m_min']]
print(df_selecionado_pandas)

             city_name   latitude   longitude  weather_code  \
0             Alaminos  16.156111  119.981110           2.0
1             Alaminos  16.156111  119.981110           1.0
2             Alaminos  16.156111  119.981110           0.0
3             Alaminos  16.156111  119.981110           1.0
4             Alaminos  16.156111  119.981110           1.0
...                ...        ...         ...           ...
504109  Zamboanga City   6.913480  122.069611           2.0
504110  Zamboanga City   6.913480  122.069611          51.0
504111  Zamboanga City   6.913480  122.069611          53.0
504112  Zamboanga City   6.913480  122.069611          53.0
504113  Zamboanga City   6.913480  122.069611          61.0

        temperature_2m_max  temperature_2m_min
0                     29.3                25.4
1                     28.4                24.7
2                     29.0                25.1
3                     29.3                24.8
4                     28.9                24.3
...                    ...                 ...
504109                29.7                25.7
504110                29.2                25.7
504111                29.2                26.0
504112                29.4                25.9
504113                28.5                25.3

[504114 rows x 6 columns]

In [ ]:
# Seleciona colunas específicas - PySpark
df_selecionado_spark = df_pyspark.select('city_name', 'latitude', 'longitude', 'weather_code','temperature_2m_max', 'temperature_2m_min')

In [ ]:
# Filtra linhas onde coluna1 = 'Alaminos' - Pandas
df_filtrado_pandas = df_pandas_weather[df_pandas_weather['city_name'] == 'Alaminos']

In [ ]:
# Filtra linhas onde coluna1 = 'Alaminos'- PySpark
df_filtrado_spark = df_pyspark.filter(df_pyspark.city_name == 'Alaminos')

In [ ]:
# Calcula a média de coluna1 agrupada por coluna7 - Pandas
df_agregado_pandas = df_pandas_weather.groupby('city_name')['temperature_2m_max'].mean().reset_index()
print(df_agregado_pandas)

          city_name  temperature_2m_max
0          Alaminos           29.276814
1      Angeles City           29.817164
2          Antipolo           29.548015
3           Bacolod           28.832850
4            Bacoor           30.815713
..              ...                 ...
133        Valencia           27.583931
134      Valenzuela           29.472488
135       Victorias           30.903477
136           Vigan           28.842267
137  Zamboanga City           28.727950

[138 rows x 2 columns]

In [ ]:
# Calcula a média de coluna1 agrupada por coluna7 - PySpark
from pyspark.sql.functions import avg

# Calcula a média de coluna1 agrupada por coluna2
df_agregado_spark = df_pyspark.groupBy("city_name").agg(avg("temperature_2m_max").alias("media_days_left"))
df_agregado_spark.show(5)

+------------+------------------+
|   city_name|   media_days_left|
+------------+------------------+
|Legazpi City| 29.10656994251297|
|   Koronadal| 29.16980563920072|
|        Bogo| 28.31437174924719|
|       Biñan|29.415411990145053|
|     Dagupan|28.750725431152542|
+------------+------------------+
only showing top 5 rows

In [ ]:
# Junção de dois DataFrames pandas
#df1 = pd.read_csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv")
#df2 = pd.read_csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv")
# df_juncao = pd.merge(df1, df2, on="city_name", how="left")

In [ ]:
# Junção de dois DataFrames PySpark
df1 = spark.read.csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv", header=True, inferSchema=True)
df2 = spark.read.csv("/root/.cache/kagglehub/datasets/bwandowando/philippine-cities-weather-data-2000-2009/versions/1/daily_data_combined.csv", header=True, inferSchema=True)
df_juncao = df1.join(df2, on="city_name", how="left")